### ISSUE TITLE
MIDI controls 1-8 weird track control behavior (Reaper)

### ISSUE THREAD

**Issue by mkruselj** [surge-synthesizer/surge#1412]
1. Lload Surge in Reaper
2. Click on any of the 8 macro sliders
3. Click on Param button in Reaper's plugin header, then Show in track controls
4. Try moving the track control up/down

As you reach the min or max value, you will see it is slowing down asymptotically, never fully showing 0.00% or 100.00%. Other automatable controls don't seem to behave like this.

![asymptote](https://user-images.githubusercontent.com/2393720/70568674-a4146380-1b98-11ea-97eb-f4452ea143c0.gif)

Note in the GIF that in some cases you can also see the param value display changing on its own, without interacting with the track control at all

**Comment by baconpaul** [comment]
Thanks. Let me at least figure out why before 165 and see if a fix is doable - so tagging 165

**Comment by baconpaul** [comment]
Need to fix #1347 before I can attack this one (since the VST3 doesn't actually handle that control correctly; I know you used the VST2 to make this graphic but you know)

**Comment by baconpaul** [comment]
So. This is actually a feature. Kind of. We may want to change it in the future but it's not a bug so I'm knocking it out of 1.6.5 since "fixing" this would be a behavior change

The UI elements and parameters for the midi controls are modulation sources and map directly to them

https://github.com/surge-synthesizer/surge/blob/e0e69231765b9fadedf25ccb17d3bbacfa58ed76/src/common/ModulationSource.h#L204

You can see that this modulation source process has an approach to a target, so it changes smoothly. The speed is fixed in the code. 

When you edit with the UI, the SurgeGUIEditor calls "set_target01" so draging the mouse doesn't do an instantaneous change but rather starts the motion along its way. That is reflected in the actual value of the param, which is why you see what you do. This is true in the VST3 now that I've fixed it also. (The AU is still messed up on the special controls).

So happy to debate what we should do here; but gonna leave it be for 1.6.5 since the code is doing what it has always done.

**Comment by mkruselj** [comment]
This issue seems fixed now that 1.6.5 is out!

**Comment by mkruselj** [comment]
Reopening this because the issue is still there.

I assume this slewing is in there because macros are MIDI learnable and MIDI CCs are 0-127 only, so this smooths out the coarseness (also prevents really fast edits). But macros are also host automatable, and in this case there should be no, or extremely minimal smoothing (just linear within a processing block, say). I suggest this to be handled like that :)

**Comment by mkruselj** [comment]
@baconpaul as per #2638, the good solution for this is to have Smoothing submenu in the main Menu with current setting, and a couple more levels of smoothing, including no smoothing. Retains the behavior of old projects, but allows greater flexibility for other use cases.
