### ISSUE TITLE
Tape kills audio when oversampled

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/surge#6834]
Load a Surge in Reaper
Oversample it to 196k 
Latch or something
Load the tape FX
Sound dissappears.

**Comment by ritschwumm** [comment]
.oO(NaN-poisoning?)

**Comment by Andreya-Autumn** [comment]
Yes maybe. 

Notably, this only happens if the oversampling is already in effect when loading the Tape, so initialization-related probably.

**Comment by baconpaul** [comment]
right so at 192 in my debug build pulling in a tape on an empty surge just sends CPU to 100%
let me try a release build to check also

**Comment by baconpaul** [comment]
OK so if you do this at 192 and run the mix the original sound comes back so the FX isn't borked completely
If you do it at 96 you get a big cut but not to 0

I really think this is somewhere in the DSP missing a sample rate reset but i can't see where.

**Comment by Andreya-Autumn** [comment]
Push out of milestone so we can 1.2 sooner?

**Comment by baconpaul** [comment]
Maybe 

I’m curious about the init cycle part thoiugh so let’s leave it float for a bit

**Comment by mkruselj** [comment]
We probably need @jatinchowdhury18's eyes on this one, I guess?

**Comment by baconpaul** [comment]
yes i think we will. i'm not seeing it.

**Comment by jatinchowdhury18** [comment]
I believe we spoke about this issue a little while ago on the Discord... If I remember right, the bug was only presenting itself when using smaller block sizes? I remember having some trouble reproducing this one as well.

**Comment by baconpaul** [comment]
I saw it at 32 yesterday in reaper once I learned how to oversample by track

**Comment by jatinchowdhury18** [comment]
Hmmm, I did some more testing today, and still haven't been able to reproduce. Currently I'm testing with the nightly VST3 in Reaper 6.68. I've tried both "Chain oversampling" and "FX instance oversampling", but maybe there's some other way of doing per-plugin oversampling in Reaper?

Just trying to narrow down what could be the differences.

**Comment by mkruselj** [comment]
Those are the only ways to do plugin oversampling in Reaper AFAIK.

**Comment by jatinchowdhury18** [comment]
Hmm okay... I was also testing on my M1 Mac. Maybe the issue only shows up on Intel? Or only on Windows? I can give those a try tomorrow.

**Comment by Andreya-Autumn** [comment]
Oh hey, Nimbus does it too it seems.

**Comment by baconpaul** [comment]
My suspicion is that reaper oversampling is doing something like: creating at sample rate SR then resetting sample rate to SR * 4. 

These FX - I bet - are dealing fine with arbitrary SR but have a bug in SR reset.

They will be different bugs - I'm really quite sure tape doesn't use libsrc

One thing to try would be to put a print statement in 'SurgeStorage::setSampleRate' and see what values reaper provides us when.

This is just a guess but its a guess which fits the evidence presented I think.

**Comment by baconpaul** [comment]
Nimbus is a separate bug of breaking when the oversampling ratio fills two blocks to make a Inout down sample block

**Comment by baconpaul** [comment]
Nimbus was fixed in 1.2.0 so renaming this issue back to just tape

**Comment by mkruselj** [comment]
@Andreya-Autumn I am not sure I can reproduce this one anymore, how about you?

**Comment by baconpaul** [comment]
I wonder if ti is the same sample reset change issue that the BBD Ensemble had? @jatinchowdhury18 ?

**Comment by mkruselj** [comment]
It seems Tape effect is setting SR related stuff in init() but sampleRateReset() virtual method is not overriden. So that might be the case!

**Comment by Andreya-Autumn** [comment]
So that PR doesn't solve it unfortunately. But it did change something, which opened some new leads. With that change, more of the noise added by "amount" survives the oversampling. Interestingly it's amplitude is samplerate-dependent (quieter with more OS), but not its frequency response. 

Investigating some more led to the realization that the signal is actually still there, but extremely quiet! Specifically:

Load Init Sine and play a fifth, peaks around -14dB here. 
Oversample 8x and load Tape - Init
Add 72dB of gain (limiter advised obviously)
The sine is back!

**Comment by mkruselj** [comment]
OK I guess we should loop in @jatinchowdhury18 again at this point, hehe 🙂

**Comment by Andreya-Autumn** [comment]
Yup! 

Oh and also, I tried running the sound card at 96k and 192k, instead of using the reaper oversampling. Same issue occurs, so it may not reaper specific after all.

**Comment by Andreya-Autumn** [comment]
We should not merge it because ultimately it didn't change the core problem. It indirectly helped me find out the things I wrote above, but no reason to merge a change that doesn't fix anything. We can leave it hanging for reference I guess?

**Comment by mkruselj** [comment]
Sure I could mark it not to close the issue but the thing is it is now doing what it was supposed to do, which is respond to `sampleRateReset()`, which it didn't. :)
