### ISSUE TITLE
Surge crashes in menu animation (Linux)

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge#813]
as @fonkle reported in #808:

I have tested the nightly build with these code changes in Bitwig and Carla, and it still has the -minor- stability issue:

If I repeatedly modify the Mouse Behavior setting and adjust some sliders in turn while playing some MIDI notes, Surge seems to crash on choosing any of the new menu items.

I have tried to catch one of these crashes in the debugger. I can only get that to work attaching to Carla running Surge-Debug.so. Sometimes it stops on line 1072 of /vstgui.surge/vstgui/lib/cframe.cpp, and at other times the debugger does not pause at all yet the plugin gets disabled (red icon) in Carla.

I cannot determine the cause of this instability, but it seems not directly related to the committed changes. Possibly it's related to vstgui?

Although the instability is very small since most people likely set the Mouse Behavior just once per system, I think it should be fixed so Surge becomes rock solid. The improvement in usability justifies the release of the changes imo, but I thought you should know.

Update: The Enable / Disable MPE-menu item has this issue as well, confirming it is not related to the changes in this commit.

You mentioned creating a stack trace previously, can you give me a hint how to do that?

**Comment by baconpaul** [comment]
So nothing obvious from looking at the code comes to mind. Some thoughts

1. Ifyou run in Carla-single (which is described in the developer guide) you can run it under gdb using standard approach to start any executable. That’s generally how I ran it on linux to a crash.
2. Alternately you can set a coredumpsize unlimited and attach to the core after the fact
3. In both models the symbols will be there in the dll but not in the host of course. But that’s OK especially since Carla-single is very transparent
4. I wonder if there’s a threading difference. All this code *should* happen on the ui thread but I would add a few carefully chosen `std::cout<<pthread_self()<<std::endl` Around the code to see if there is some threading or multiple calling coming on
5. The linux menus gave us a lot of trouble at the outset in vstgui. Iwouldn’t put it past there being some bug there. (Including the thread one but maybe something else). There’s a linux tagged issue on our current complaints and concerns with them.
6. I never really understood the linux vst2 threading model @falkTX put in place in detail but if you look in src/vst2 there’s a linux vst2 class which is injected in the class hierarchy to do loops and timers. Not saying that’s wrong or to blame but if you get what sounds like thread conflicts it could be required to understand that.
7. It might not be thread conflicts at all! A debugger will help if you can catch a break.

Good luck!

I haven’t seen a crash in the mac code (except when I have it pulled apart in pieces) in months so my gut is this is something linux specific. But that’s just gut.

**Comment by fonkle** [comment]
I am looking into this issue. First of all the title of the issue is wrong. It's not Linux that crashes, but Surge. I can debug it using carla-single and it crashes in the animation code of VSTGUI (in SurgeGUIEditor::idle()).

Also, it occurs while not playing notes as well.

Could you please change the title to something like: "Crash on menu animation (Linux)"? Thx!

**Comment by baconpaul** [comment]
Sure! And if it is in menu, also linking to #617 

Linux menus are rather painful. Good luck! I spent some time with em 2 months ago and wrote down thoughts in that issue and also remember some of it so if you get stuck happy to offer what I remember!

**Comment by fonkle** [comment]
This is a bug in VSTGUI. It crashes in _cframe.cpp_:
```
/**
 * @param pView view which was removed
 */
void CFrame::onViewRemoved (CView* pView)
{
        removeFromMouseViews (pView);

	if (pImpl->activeFocusView == pView)
		pImpl->activeFocusView = nullptr;
	if (pImpl->focusView == pView)
	{
		if (pImpl->active)
			setFocusView (nullptr);
		else
			pImpl->focusView = nullptr;
	}
	if (auto container = pView->asViewContainer ())
	{
		if (container->isChild (pImpl->focusView, true))
			setFocusView (nullptr);
	}
	if (getViewAddedRemovedObserver ())
		getViewAddedRemovedObserver ()->onViewRemoved (this, pView);
	if (pImpl->animator)
		pImpl->animator->removeAnimations (pView);
        if (pView->wantsWindowActiveStateChangeNotification ())          <----- HERE
                pImpl->windowActiveStateChangeViews.remove (pView);
}
```
Probably the _pView_ pointer is invalid there.

I tried using a newer version of the VSTGUI sdk, but that gave another segmentation fault in _cairo_scaled_font_status_, as @baconpaul has reported this january: https://github.com/steinbergmedia/vstgui/issues/88.

So I am somewhat stuck here. It's not the end of the world, since most people set the value through the menu only once, but it is messy...

**Comment by baconpaul** [comment]
We have patches in our vstgui. If you figure out a bit of code you want injected there (probably “if ! Pview return”) I can put it in our fork of vstgui easily. Did it yesterday for Mac mouse actually!

**Comment by fonkle** [comment]
Nah, I have already tried that. _pView_ is not empty, but somehow calling _wantsWindowActiveStateChangenotification()_ on it triggers a segmentation fault. I don't know why, perhaps is was already deleted by then? I also added a function to test _pView_ for an empty private member _pImpl_, but that didn't work either.

**Comment by baconpaul** [comment]
Huh ok! Well we found and patched some things - that’s why we forked vstgui (see doc/vstgui.md or some such) so if you find it we can fix it no problem.

Easy way to repel or just click a lot in menus?

**Comment by baconpaul** [comment]
Repel is iPhone for repro :)

**Comment by fonkle** [comment]
Alas, click a lot. Usually within a click or 5, but mileage may vary :).

**Comment by baconpaul** [comment]
The fact that that method isn’t override and is a simple return false means something else has corrupted pview or its vtable and im sure you know! Ugh. Tough.

**Comment by fonkle** [comment]
Yeah. I have been looking into the Steinberg vst3sdk but that is rather gnarly too. The _audiohost_ diagnostic application in there won't even compile on Linux (issue #34) . So tbh I am kinda stuck on all fronts.

**Comment by baconpaul** [comment]
Yeah OK. I'll try and see if I can see anything this week! Have a bit of time weds.

**Comment by baconpaul** [comment]
Hey just reading the code I have a theory what the bug is. I don't have linux running now so let me share it here. 

The code right before your crash is removeAnimation. Here's the implementation of that in `vstgui.surge/vstgui/lib/animation`

```
void Animator::removeAnimation (CView* view, IdStringPtr name)
{
        pImpl->animations.forEach ([&] (const SharedPointer<Detail::Animation>& animation) {
                if (animation->view == view && animation->name == name)
                {
#if DEBUG_LOG
                        DebugPrint ("animation removed: %p - %s\n", view, name);
#endif
                        if (animation->done == false)
                        {
                                animation->done = true;
                                animation->animationTarget->animationFinished (view, name, true);
                        }
                        pImpl->animations.remove (animation);
                }
        });
```

Now notice that does a `forEach` which basically iterates over the container applying that proc. But that proc does a `pimple->animations.remove(animation)`

The internal structure of animations contains a std::vector as the contents. remove does a remove from this.

So this code is basically iterating over a vector while it modifies the vector. That's one of the surefire ways to cause a crash in STL.

I think the fix is to edit that function to be something like this

```
void Animator::removeAnimation (CView* view, IdStringPtr name)
{
        std::vector<SharedPointer<Detail::Animation> removeThese;
        pImpl->animations.forEach ([&] (const SharedPointer<Detail::Animation>& animation) {
                if (animation->view == view && animation->name == name)
                {
#if DEBUG_LOG
                        DebugPrint ("animation removed: %p - %s\n", view, name);
#endif
                        if (animation->done == false)
                        {
                                animation->done = true;
                                animation->animationTarget->animationFinished (view, name, true);
                        }
                       removeThese.push_back(animation);
                }
        });

       for(auto an : removeThese)
           pImpl->animations.remove(an);
```

See? Basically have the iteration collect the removal targets and once it is complete have a separate iteration to remove them so you aren't editing in place.

Too late and not enough linux running for me to test this but may want to give it a whirl?

**Comment by fonkle** [comment]
Yes, I will try it asap. Since the crash would not occur when skipped said function, this might just be the place to be :). Stay tuned.

**Comment by fonkle** [comment]
Alas, it does not work. Same segmentation fault occurs :(.

Which does make sense, because if it was indeed deleting the array while iterating, it would have been more likely to crash inside `removeAnimation()`. However, somehow pView _does_ get corrupted inside `removeAnimation()`, because the segfault does not occur when it is skipped.

**Comment by fonkle** [comment]
Interesting: If I remove the call to `removeAnimation()` the segfault is gone.

if I reduce `removeAnimation()` to this:
```
void Animator::removeAnimation (CView* view, IdStringPtr name)
{
	pImpl->animations.forEach ([&] (const SharedPointer<Detail::Animation>& animation) {
 	});
}
```
it is back, so somehow _pView_ get corrupted by the `forEach` loop itself...

My template skills do not suffice yet. Have to read up...

**Comment by fonkle** [comment]
The above is not true; there is also `removeAnimations()`. If I reduce both functions to the forEach() loop, the segfault is gone.

So, I tried your code change to both functions, but the segfault occurred.

**Comment by baconpaul** [comment]
Ok that’s great then we found it

I have a bit of time later this afternoon. I can correct the code with the right template stuff then and push a branch to vatgui for you to test probably around 5pm eastern and if it works we can merge it into master

Great team debugging here! Good stuff

**Comment by fonkle** [comment]
Nono, it's not fixed yet. It doesn't crash if I comment those 2 lines out, but then the animations don't get removed.

That line (in 2 locations) followed by the next iteration of forEach() corrupts pView somehow.

**Comment by baconpaul** [comment]
Yeah I know. 

The way it corrupts them is that it is editing while iterating which is a nono. I will fix the code to not do that and it will be fixed.

**Comment by baconpaul** [comment]
Basically code like this

```
for( auto it = container.begin(); it != container.end(); ++it )
   if( condition )
     container.remove(*it)
```

corrupts memory. That's what animations is doing.

**Comment by baconpaul** [comment]
On and the fix is

```
std::vector<thingy> removeThese;
for( auto it = container.begin(); it != container.end(); ++it )
   if( condition )
     removeThese.push_back(*it);
for( auto v : removeThese )
   container.remove( v );
```

then you never modify the container you are iterating over.

**Comment by baconpaul** [comment]
OK @fonkle I had a few minutes this morning. In your surge do this

```
git checkout master
cd vstgui.surge
git fetch origin
git checkout linux-anim-vector
cd ..
./build-linux cleanall
```

then try a build. Let me know if that fixes the crashes.

After the checkout of linux-anim-vector you should see this

```
paul@ubuntu:~/surge$ grep -r std::vector vstgui.surge/vstgui/lib/animation/
vstgui.surge/vstgui/lib/animation/animator.cpp:        std::vector<SharedPointer<Detail::Animation>> toRemove;
vstgui.surge/vstgui/lib/animation/animator.cpp:        std::vector<SharedPointer<Detail::Animation>> toRemove;
```

which means you have my diffs. 

If that code doesn't crash I can move that branch over into master.

Best

**Comment by fonkle** [comment]
Did exactly as you said, but it isn't working either. Sorry :).

The corruption takes place inside of `pImpl->animations.remove (animation);`. Comment it out and the segfault if gone; both in the original and the patched code...

**Comment by baconpaul** [comment]
Huh and you are sure you are building the new code? The .remove is moved in the new code right? Can you put a dumb syntax error in and make sure you are getting a compile?

.remove() just removes from an STL container. If you do that in foreach you will corrupt memory so the code was wrong; but that may not be the only thing wrong.

If I could make it crash I would debug of course but I haven't been able to :(

In the "comment out state that works" can you put the output of `(cd vstgui.surge && git diff)` into this issue?

**Comment by baconpaul** [comment]
Also: `(cd vstgui.surge && git diff surge)` shows the diffs right?

**Comment by baconpaul** [comment]
And just to be sure: you see this in the code you are building

```
void Animator::removeAnimations (CView* view)
{
        std::vector<SharedPointer<Detail::Animation>> toRemove;
        pImpl->animations.forEach ([&] (const SharedPointer<Detail::Animation>& animation) {
                if (animation->view == view)
                {
#if DEBUG_LOG
                        DebugPrint ("animation removed: %p - %s\n", view, animation->name.data ());
#endif
                        if (animation->done == false)
                        {
                                animation->done = true;
                                animation->animationTarget->animationFinished (view, animation->name.data (), true);
                        }
                        // pImpl->animations.remove (animation);
                        toRemove.push_back(animation);
                }
        });
        for(auto v : toRemove)
          pImpl->animations.remove(v);
}

```

right?

**Comment by fonkle** [comment]
Yes, very sure :).

This is the result of (cd vstgui.surge && git diff):
```
diff --git a/vstgui/lib/animation/animator.cpp b/vstgui/lib/animation/animator.cpp
index 741beb5e..70679ced 100644
--- a/vstgui/lib/animation/animator.cpp
+++ b/vstgui/lib/animation/animator.cpp
@@ -300,7 +300,7 @@ void Animator::removeAnimation (CView* view, IdStringPtr name)
                                animation->done = true;
                                animation->animationTarget->animationFinished (view, name, true);
                        }
-                       pImpl->animations.remove (animation);
+                        //pImpl->animations.remove (animation);
                }
        });
 }
@@ -319,7 +319,7 @@ void Animator::removeAnimations (CView* view)
                                animation->done = true;
                                animation->animationTarget->animationFinished (view, animation->name.data (), true);
                        }
-                       pImpl->animations.remove (animation);
+                        //pImpl->animations.remove (animation);
                }
        });
 }
```

**Comment by baconpaul** [comment]
Yes but that diff doesn't have my changes! See above. Somehow you have not pulled the version I corrected.

**Comment by baconpaul** [comment]
What does `(cd vstgui.surge && git status)` and `(cd vstgui.surge && git remote -v)` say?

**Comment by baconpaul** [comment]
Oh if you have diffs I bet the checkout failed. Try this

```
cd vstgui.surge
git fetch origin
git stash
git checkout linux-amin-vector
```

and post the output here?

**Comment by baconpaul** [comment]
linux-anim-vector of course.

Basically if your removeAnimations doesn't have the "toRemove.push_back" replacing the "pImpl->animations.remove(animation)" you haven't pulled the fixed version. Which would explain why it isn't fixed at least! :)

I'm offline for a while now. Good luck!

**Comment by fonkle** [comment]
No the diff I posted was in response to this:
> In the "comment out state that works" can you put the output of (cd vstgui.surge && git diff) into this issue?

It's the version in which I get no segfault.

I have pulled and tested your code before that; I even tested the diff for these 2 lines:
```
vstgui.surge/vstgui/lib/animation/animator.cpp:        std::vector<SharedPointer<Detail::Animation>> toRemove;
vstgui.surge/vstgui/lib/animation/animator.cpp:        std::vector<SharedPointer<Detail::Animation>> toRemove;
```
But that really does not solve the segfault. The problem seems to be even deeper than that, somewhere in the template stuff included in vstgui. Like _dispatchlist.h_?

I must say that I am rather disappointed in the quality of the vst3sdk and vstgui so far. It always seems to come down to fixing the SDK itself rather than the project it was used for. I a couple of days I have run into 3 showstopper issues with no sign of any development or even interest from Steinberg Media.  Fighting with _vstgui_ in Linux is starting to feel like wasting time tbh.

**Comment by baconpaul** [comment]
Yeah I agree it is not awesome - I have fixed and worked around a lot of bugs

Dispatchlist is just a wrapper on some stl which makes the api worse. I agree the problem is there somewhere. Lemme look some more tomorrow.

**Comment by baconpaul** [comment]
Oh also: all the time I’ve been getting surge up and running I’ve been thinking of ripping out vstgui and replacing it with nanovg plus glew on windows and Linux and nanovg plus cocoa/core graphics on Mac. I am actually most of the way to getting a pure cocoa/cg backend for nanovg working!

But decided to go 1.6 with the code the way we got it. Wonder if that’s a mistake?

The real thing is: at some point there’s a max investment in surge. It’s a great synth. Let’s patch it up and call it 1.6. Then if we want to fix some of the big problems (lack of ui separation; dependence on vstgui) at least people have a synth in hand.

**Comment by fonkle** [comment]
I agree, despite vstgui and even this segfault (most menu setting are systemwide so not used often) Surge is already quite usable on Linux as it is now. So that's a good thing.

On the long term replacing vstgui seems like a good choice, although in a way, that also means rewriting substantial parts of vstgui. So that is a big decision to make :).

I am afraid my c++11 skills won't let me fix the segfault in a day or two (although I think we were close).

**Comment by baconpaul** [comment]
Yeah I will poke around and see if I see other culprits tomorrow; have a bit of time - agree we are close

**Comment by baconpaul** [comment]
oh good grief. dispatch list has a bunch of nonsense in it which behaves differently in forEach with removal of elements so the "remove" is "safe" (inasmuch as it edits a value and cleans up when foreach exits) but there's a lot of code for me to stare at to determine if it is right or not. Ugh. 

And the code like "postForEach" just looks nuts to me. Why even make the toRemove vector for instance.

I kinda feel like the entire class could be removed if you just wanted to use `std::transform` too.

Maybe try running with DEBUG_LOG set to 1? 

But another thing to try is: lets just disable animation on menu close. It is all dumb anyway. Basically fading menus to 0.  So here's something for you to tru

1. in lib/platform/common/genericoptionmenu.cpp for closeSubMenu change the default for allowanumation from true to false. That may just fix it. But also

2. Same file try just commenting out decorView->addAnimation 

3. The third animation comes later. You can remove the addAnimation but then you need to do the things that are in the lambda so try this one last

I think this approach may at least stop it crashing.

Hard annoying problem.

Finally: See if any of this has changed in the upstream develop branch at steinberg. Sometimes they fix things?

Sorry to not have a better answer :(

**Comment by fonkle** [comment]
I set DEBUG_LOG to 1. Turned out Surge only segfaults when more than one animations are removed, so inside `Animator::removeAnimations()` but NOT in `Animator::removeAnimation()`. But the code (dispatchlist.h) just gets too messy (at least for me) to debug any further than that.

Next, if I force _allowAnimation_ to false in `closeSubMenu()` in _genericoptionmenu.cpp_ a different segfault is triggered (about as often as the original one). But, if set to true, it triggers the original segfault instantly (so not after a few tries).

Commenting out `view->addAnimation()` in `closeSubMenu()` in genericoptionmenu.cpp seems to -finally- to the trick. And tbh, I don't even notice a significant difference in menu opacity animation.

This call could be removed for Linux only, though it still is weird that it only surfaces in Linux. But I would be happy to include this as a fix, at least for now. I shall do some more testing this afternoon.

**Comment by fonkle** [comment]
Not sure how it works with vstgui.surge being a submodule though. Can I modify that and create a PR?

**Comment by baconpaul** [comment]
Wonderful!

The submodule patching is a pain. Easier for me to do it if you just attach a diff to this issue and I’m happy to do so and it’s probably quicker anyway.

The reason it only shows up on Linux is Mac and windows use native menus; and Linux has no native menus. This code is linux only.

**Comment by baconpaul** [comment]
So basically get your vstgui.seuge in the state you want then copy and paste the entire output of “cd vstgui.surge && git diff surge” here.

Thanks!

**Comment by fonkle** [comment]
Ok I tested some more and I really cannot get it to segfault anymore. This is the diff:
```
diff --git a/vstgui/lib/platform/common/genericoptionmenu.cpp b/vstgui/lib/platform/common/genericoptionmenu.cpp
index 58fe6a89..771917d6 100644
--- a/vstgui/lib/platform/common/genericoptionmenu.cpp
+++ b/vstgui/lib/platform/common/genericoptionmenu.cpp
@@ -266,14 +266,14 @@ private:
                        {
                                auto view = shared (subMenuView);
                                subMenuView = nullptr;
-                               view->addAnimation (
+/*                             view->addAnimation (
                                    "AlphaAnimation", new AlphaValueAnimation (0.f, true),
                                    new CubicBezierTimingFunction (
                                        CubicBezierTimingFunction::easyIn (theme.menuAnimationTime)),
                                    [view] (CView*, const IdStringPtr, IAnimationTarget*) {
                                            if (view->isAttached ())
                                                    view->getParentView ()->asViewContainer ()->removeView (view);
-                                   });
+                                    }); */
                                if (db)
                                {
                                        if (auto frame = db->getFrame ())
```
It's just lines 269-276 commented out of `genericoptionmenu.cpp`. Minimal visual impact. Fixes this annoying issue afaic.

Can you keep this patch applied after updating vstgui.surge?
Do you think I should report this issue to vstgui?

**Comment by baconpaul** [comment]
I think opening an issue on vstgui with this as the correction is a good idea.

And yes we can keep this patch applied. I just need to do some git wrangling. We forked vstgui for exactly this reason (and have 6 or 7 other permanent patches in place). Can probably do it today. If not by the weekend for sure.

**Comment by baconpaul** [comment]
And thank you!

**Comment by baconpaul** [comment]
Right because the end of the animation hides it. You need to find somewhere where it does an animation->go() or some such and replace that with a hide. What a pain.

**Comment by fonkle** [comment]
I noticed that in the `view->addAnimation()` code there was callback code to be called when the animation was finished, removing the view (pView) which would cause the segfault later on.

Then I found this: https://github.com/steinbergmedia/vstgui/issues/40. In there is suggested that the situation can be caused by erroneously constructing VSTGUI objects.

So then I thought it might have to do with `mpeSubMenu->forget();` in _SurgeGUIEditor.cpp_.

Spent hours again figuring out if the error can be prevented in SurgeGUIEditor, but to no avail. It just seems like all works fine with just a few entries in the options menu, but timing issues make it crash when a few more (as in: the Mouse Behavior menu) are added.

The best solution is to comment out lines 274 and 275 of _genericoptionmenu.cpp_. That would probably cause a small memoryleak but at least then Surge will not crash.

**Comment by baconpaul** [comment]
The forget in SurgeGUIEditor should be OK since the menu was added to a parent so doesn't need remembering by the editor. I agree it sort of smells like a refcount is off somewhere though.

The ReferenceCount implementation (in vstguibase) also has the dreaded "delete this" which can totally screw you if you end up out of order. You get a pointer to something which is toast because you don't remember it right. But that does make me think perhaps not everything in SurgeGUIEditor is being forgotten. Let me look there quickly on my mac and see if anything comes to mind.

**Comment by baconpaul** [comment]
Hey so I have a little theory. Do you mind testing it for me?

My theory is that the addAnimation isn't increasing the reference count. So you can get an object ultimately forgotten which is de-animating. This means you are using deleted memory for draws which would match what you see (occasional crashes unpredictably, more the more allocators-things you do).

So before we comment out that could you try in vstgui.surge/vstgui/lib/cview.cpp in both the addAnimation methods add a line 'remember()' right after the assert; and in the removeAllAnimations inside the if block but after the removrAnimations add a 'forget()' so we can remember this is remembered appropriately through an animation sequence.

If that doesn't work then I will comment out the lines you suggest in linux and push a patch. Just not worth fighting this any more. But lets just try that first.

Thanks!

**Comment by fonkle** [comment]
I did as you suggested, but now it segfaults at line 1430:
![image](https://user-images.githubusercontent.com/47926665/56313170-3c656000-6152-11e9-8dd8-e61530c17e5a.png)

**Comment by fonkle** [comment]
Would it be an idea to post the entire code of `SurgeGUIEditor::showSettingsMenu` in an issue in stenbergmedia/vstgui?

**Comment by fonkle** [comment]
I opened an issue with steinbergmedia/vstgui: https://github.com/steinbergmedia/vstgui/issues/108.

Hopefully anyone there can be of help :).

**Comment by baconpaul** [comment]
Thanks! Let’s see if we hear anything!

**Comment by fonkle** [comment]
It took a while, but there seem to be improvements going on regarding the (generic) option menu. I'll have a look if this improves the situation.

Also, the audiohost in the vst3sdk was fixed (for linux). This could be good for debugging the vst3 version?

**Comment by baconpaul** [comment]
Good news on menus! Let us know what you find!

On vst3 I was always able to get the Steinberg host running. Then we get a crash I. Surge because the ui is not initialized because we don’t hook into the runloop. Issue #514 shows how far I got. Would be happy for someone to give a whirl there ... it’s tricky since we do single class vst3 not dual but I think it’s just debugging and figuring out what’s missing. 

Appreciated!

**Comment by fonkle** [comment]
I can load and play the VST3 version of Surge, without GUI, in the -recently fixed- _audiohost_ example included with the vst3sdk.

To circumvent a crash however I had to change the filename from Surge-Debug.so to Surge-Debug.64.so. Other plugins install a symbolic link in the ~/.vst3 folder called _filename.so_ which points to a shared library in the home folder (but not in .vst3) called _filename.64.so_.

Should the Linux package script rename the file to Surge(-Debug).64.so?

Also, the VST3 package script for Linux does not work with the debug version (Surge-Debug.so) of Surge. Could be fixed in the package script as well...?

**Comment by baconpaul** [comment]
So that’s great. 

The packaging stuff was set up in this pr

https://github.com/surge-synthesizer/surge/pull/646

Which has a link to associated issues and the Steinberg doc. The trick is: make a bundle not a raw .so. Beyond that I know nothing I’m sorry!

**Comment by fonkle** [comment]
I will study the vst3sdk documentation some more and see if I can improve the packaging script. It doesn't seem too hard.

2 things can be improved imo:

1. When building Surge (VST3) with debug information, the output is called _Surge-Debug.so_ (instead of _Surge.so_) and so the package script fails. It should work with both release and debug builds.

2. I think (I'll have to check this in the vst3sdk docs) that the shared library extension should be _.64.so_ (_.32.so_?) instead of _.so_. The plugin can then be loaded in the _audiohost_ example of the vst3sdk.

More to come.

**Comment by baconpaul** [comment]
Yeah the odds of it being right the way I have it now are really low! 

I got it to load in the old editor host, committed it, and then realized it didn't work well and left it there. 

So happy for you to change whatever you need and fire over a pull request. Especially since it doesn't work at all right now any change you want to share will be great in Linux VST3 land!

**Comment by baconpaul** [comment]
Hey just an FYI that @jpcima and I finally removed menu animation in surge’s vstgui fork which greatly improves things; and also I got the VST3 working in reaper and not crashing in Bitwig. These features are all in the nightly so I’m going to close this issue.
